# -*- coding: utf-8 -*-
"""Text to Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtoMFEwUzq-0L_dyPkgJwhLt2pStZA28
"""

!pip install diffusers transformers gradio accelerate

from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
import torch

!pip show torch

model_id1="dreamlike-art/dreamlike-diffusion-1.0"
model_id2="stabilityai/stable-diffusion-xl-base-1.0"
pipe=StableDiffusionPipeline.from_pretrained(model_id1,torch_dtype=torch.float16,use_safetensors=True)
pipe=pipe.to("cuda")

def generate_image(pipe,prompt,params):
  img=pipe(prompt,**params).images
  num_images=len(img)
  if num_images>1:
    fig,ax=plt.subplots(nrows=1,ncols=num_images)
    for i in range(num_images):
      ax[i].imshow(img[i])
      ax[i].axis("off")
  else:
    fig=plt.figure()
    plt.imshow(img[0]);
    plt.axis("off")
  plt.tight_layout()

prompt="Satellite view of A busy airport with many aeroplanes."
params={'num_inference_steps':25,'num_images_per_prompt':5,'width':512,'height':int(1.5*640)}
generate_image(pipe,prompt,params)